#!/bin/sh

NC='\033[0m'
YELLOW='\033[1;33m'
RED='\033[0;31m'

# format
echo -e "${YELLOW}Running pre-commit hook, dotnet format...${NC}"
dotnet format --no-restore --verbosity detailed
rc=$?
if [[ $rc != 0 ]] ; then
    echo -e "${RED}Failed to format project, please fix this and commit again${NC}"
    exit $rc
fi

exit 0